#dataset configuration
dataset:
    name: MnistDataset
    path: D://datasets/mnist/
    shape: [1,28,28]
    num_class: 10
    task_classifier: multi-classification
    task_confidnet: binary-classification
    OOD:
        name: FashionMnistDataset
        path: D://datasets/fashion-mnist/

#training configuration
training:
    batch_size: 256
    classifier_epoch: 2
    confidnet_epoch: 2
    finetuning_epoch: 1
    num_worker: 0
    drop_last: True
    loss_classifier: CrossEntropyLoss
    loss_confidnet: MSELoss
    optimizer:
        name: SGD
        lr: 0.001
        lr_finetuning: 0.0001
        momentum: 0.9
        weight_decay: 0.0001

#evaluation configuration
evaluation:
    batch_size: 512
    num_worker: 0
    drop_last: False
    metrics: ['accuracy','balanced_accuracy','AUROC','ECE','FPR']

#model configuration
model:
    name: ConvNetMNIST
    path: models/
    transfered:
    num_feature: 64
    parallel: False
